# -*- coding: utf-8 -*-
"""Python Basic Assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOAh5g4tCnwPFF6VPh8TV7t7y1COxwjF
"""

print("Task 1: Variables and Data Types")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
fav_number = float(input("Enter your favorite number: "))

print(f"Hello, {name}!")
year_turn_100 = 2025 + (100 - age)
print(f"You will turn 100 years old in the year {year_turn_100}.")
print(f"Your favorite number doubled is {fav_number * 2}.\n")

print("Task 2: Conditional Statements")
num = float(input("Enter a number: "))
if num % 2 == 0:
    print("The number is Even.")
elif num % 2 == 1:
    print("The number is Odd.")
else:
    print("The number is not an integer, so neither even nor odd.")
if num > 0:
    print("The number is Positive.")
elif num < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.\n")

print("Task 3: Loops")
print("Even numbers from 1 to 50 using a for loop:")
for i in range(2, 51, 2):
    print(i, end=' ')
print("\nEven numbers from 1 to 50 using a while loop:")
i = 2
while i <= 50:
    print(i, end=' ')
    i += 2
print("\n")

print("Task 4: Lists and Dictionaries")
foods = []
for i in range(5):
    food = input(f"Enter favorite food {i+1}: ")
    foods.append(food)

print("Your favorite foods are:", foods)
food_lengths = {food: len(food) for food in foods}
print("Food lengths dictionary:", food_lengths)
print()

print("Task 5: Functions")
def calculate_area(shape, dimension1, dimension2=None):
    if shape.lower() == 'circle':
        return 3.14159 * (dimension1 ** 2)
    elif shape.lower() == 'rectangle':
        return dimension1 * dimension2
    elif shape.lower() == 'triangle':
        return 0.5 * dimension1 * dimension2
    else:
        return "Unknown shape"
        print("Area of circle (radius = 5):", calculate_area('circle', 5))
print("Area of rectangle (4 x 7):", calculate_area('rectangle', 4, 7))
print("Area of triangle (base = 6, height = 8):", calculate_area('triangle', 6, 8))
print()

print("Task 6: String Manipulation")
sentence = input("Enter a sentence: ")
vowels = "aeiouAEIOU"
vowel_count = sum(1 for char in sentence if char in vowels)
print("Number of vowels:", vowel_count)
reversed_sentence = sentence[::-1]
print("Reversed sentence:", reversed_sentence)
print("Uppercase sentence:", sentence.upper())
print()

print("Task 7: File Handling")
file_name = "data.txt"
with open(file_name, "w") as file:
    file.write("Hello, Python!\n")
    file.write("Learning file handling.\n")
    file.write("Python is fun!\n")
print(f"Contents of {file_name}:")
with open(file_name, "r") as file:
    contents = file.read()
    print(contents)

print("Task 8: Error Handling")
try:
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    result = num1 / num2
    print(f"The result of division is: {result}")
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except ValueError:
    print("Error: Invalid input. Please enter numeric values.")